/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "agjmgcluyzzzcjkogixl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnam1nY2x1eXp6emNqa29naXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTA4OTEsImV4cCI6MjA4Nzc2Njg5MX0.6-5xJ_NskqlZzTly7A9GWIlzxKQG-GpAtZ3mXYKSaEY"